### PR TITLE
Topic/trait edits

### PR DESCRIPTION
**Pull request by bellerbrock**
Description 
-----------------------------------------------------

Edits existing traits to add missing methods and scales and fix identified errors

Checklist 
---------------------------------------------------------------------------------------
- [x] An OBO file generated from an OWL file
- [ ] New terms
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [x] Term updates
  - [x] The relevant issue has been closed.
  - [ ] Further work is required.
- [x] CHECKS
  - [ ] New variables have a parent trait ID 
    - [ ] New variables have methods and scales 
  - [x] The OBO file has been validated
    - [x] checked in sweetpotatobase
    - [ ] checked CropOntology

### CODE REVIEW

**Comment by bellerbrock** [comment]
Ah, I see what you're saying @marieALaporte. I think I accidentally created this branch while checked out on the other branch. I'll merge this one and delete the other.

@cooperl09 I think measurements of the traits are also taken on seedling plants and small pots in the greenhouse. But I can get more details and refine the definition if these measurements are restricted to beds.

**Comment by nmenda** [comment]
@bauchetg I agree with @cooperl09 
check if the fact that the plants are in beds (Vs pots or anything else) makes the measurement unique. If not, then it should be added as a phenotypeprop 
If having the plants in beds makes the phenotypes uncomparable with similar measurements in pots, then it would make sense to have this as part of the trait name and definition

**Comment by bellerbrock** [comment]
Ok, so these traits are used elsewhere. Should be good to merge if someone could please add their review.

**Comment by bellerbrock** [comment]
@nmenda @marieALaporte @vhualla The branch is ready to merge now if someone could please add their review!

**Pull request merged**
